# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0051_auto_20200718_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefinedfielddefinition',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
