# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-13 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0052_userdefinedfielddefinition_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='import_tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
